stages:
  - test

sonarqube-check:
  stage: test
  image: gradle:alpine
  script: 
    - cd Project/Individual-Track-Project/demo
    - gradlew sonarqube -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - main

