stages:
  - sonarqube-check

sonarqube-check:
  stage: sonarqube-check
  image: gradle:jre11-slim
  script: ./gradlew sonarqube -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - master

