stages:
  - build
  - test

build:
  stage: build
  script: 
    - cd Project/Individual-Track-Project/demo
    - ./gradlew build -x test
    - ./gradlew.bat --stop

image: gradle:alpine

sonarqube-check:
  stage: test
  script: gradle sonarqube -Dsonar.qualitygate.wait=true
  only:
    - main
