stages:
  - build
  - sonarqube-check
  - test

build:
  stage: build
  script: 
    - cd Project/Individual-Track-Project/demo
    - ./gradlew build -x test
    - ./gradlew.bat --stop

sonarqube-check:
  stage: sonarqube-check
  image: gradle:alpine
  script: gradle sonarqube -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - main

test:
  stage: test
  script:
    - cd Project/Individual-Track-Project/demo
    - ./gradlew test
    - ./gradlew.bat --stop
  allow_failure: true

