stages:
  - build
  - test

build:
  stage: build
  script: 
    - cd individual_track_viktor_skachkov/Project/Individual-Track-Project/demo
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd individual_track_viktor_skachkov/Project/Individual-Track-Project/demo
    - ./gradlew test
    - ./gradlew.bat --stop
