stages:
  - test
image: gradle:alpine

sonarqube-check:
  stage: test
  script:
    - cd Project/Individual-Track-Project/demo
    - gradle sonarqube -Dsonar.qualitygate.wait=true
  only:
    - main

